#!/bin/sh

echo -e $PRIVATE_SSH_KEY > id_rsa

chmod 600 id_rsa

# to use self-signed certs with wss
#openssl req -new -x509 -days 365 -nodes -out cert.pem -keyout cert.pem -subj "/C=CH/L=Geneva/O=SixSq/CN=$HOSTNAME"

./websocket_ssh.py